/**
 * Ecosystem (plugin) map generation (fs). Ports `generate_map.py`: scans every
 * installed plugin into a level-1 `.cartographer/index.md` + per-plugin level-2+
 * trees, preserving enriched descriptions. Reuses `findMarketplacePlugins`,
 * `readPluginMeta`, `scanPlugin`, `mergeLines`, `writePluginMap`.
 */
import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { findMarketplacePlugins, readPluginMeta } from "./detect";
import { scanPlugin } from "./scan";
import { mergeLines } from "./merge";
import { writePluginMap } from "./write-plugin-map";

function pluginDirs(dir: string): string[] {
  let entries: string[] = [];
  try { entries = readdirSync(dir); } catch { return []; }
  return entries
    .filter((n) => !n.startsWith("_") && !n.startsWith("."))
    .filter((n) => { try { return statSync(join(dir, n)).isDirectory(); } catch { return false; } })
    .sort((a, b) => a.localeCompare(b, "en"));
}

function utcStamp(now: number): string {
  return new Date(now).toISOString().slice(0, 16).replace("T", " ");
}

/**
 * Generate the plugin ecosystem map under `<pluginsDir>/.cartographer`.
 * @param now - Clock for the banner timestamp.
 * @param pluginsDirOverride - Override for the marketplace plugins directory.
 * @returns The map navigation context, or "".
 */
export function generateEcosystemMap(now: number, pluginsDirOverride?: string): string {
  const pluginsDir = resolve(pluginsDirOverride ?? findMarketplacePlugins());
  try { if (!statSync(pluginsDir).isDirectory()) return ""; } catch { return ""; }
  const outputDir = join(pluginsDir, ".cartographer");
  mkdirSync(outputDir, { recursive: true });
  const dirs = pluginDirs(pluginsDir);
  const lines = [`# Ecosystem Map (${dirs.length} plugins)\n`, `> Auto-generated by cartographer — ${utcStamp(now)}\n`];
  for (const name of dirs) {
    const pluginPath = join(pluginsDir, name);
    const [version, pkgName] = readPluginMeta(pluginPath);
    const display = pkgName || name;
    const items = scanPlugin(pluginPath);
    const agents = items.filter(([t]) => t === "agent").map(([, n]) => n);
    const ver = version ? ` (v${version})` : "";
    lines.push(`- [${display}](./${display}/index.md)${ver} → ${agents.length ? agents.join(", ") : "(no agents)"}`);
    writePluginMap(outputDir, display, version, items, pluginPath);
    writePluginMap(pluginPath, ".cartographer", version, items, pluginPath);
  }
  const indexPath = join(outputDir, "index.md");
  writeFileSync(indexPath, mergeLines(lines, indexPath).join("\n") + "\n", "utf-8");
  return `Project map: .cartographer/project/index.md — navigate project files. ` +
    `Plugin skills map: ${outputDir}/index.md — navigate agent skills. ` +
    `Branches link to deeper index.md, leaves link to real files.`;
}
