import type { Prompt } from "../prompt/types";
import {
  isExcludedJsPath,
  isExcludedPhpPath,
  isExcludedSwiftPath,
  isSelfGateSourcePath,
} from "./framework-solid-exclude";
import { laravelGate, nextGate, reactGate, swiftGate } from "./framework-solid-gates";
import { goGate, rustGate } from "./framework-solid-gates-systems";
import { jsGateRoute } from "./js-gate-route";
import { extendedViolations } from "./framework-solid-extended";
import { rolloutVerdict } from "./conventions/verdict";

/** Next.js detection: directive, runtime types, or a `next` import. */
const NEXT_RE: RegExp = /(use client|use server|NextRequest|NextResponse|from ['"]next)/;

/** Build a SOLID `block` prompt from one or more violation messages. */
function block(filePath: string, violations: string[]): Prompt {
  return {
    kind: "block",
    title: "SOLID violation",
    reason: `SOLID VIOLATION in ${filePath}: ${violations.join(" ")}`,
    actions: violations,
  };
}

/** Run the JS/TS gate (React or Next.js), honoring build-artifact exclusions. */
function jsViolations(filePath: string, content: string, fileLines?: number): string[] {
  if (isExcludedJsPath(filePath) || isSelfGateSourcePath(filePath)) return [];
  // H1: manifest-first routing — the PROJECT's declared framework picks the
  // gate, so a marker-less client component in a Next.js app still gets the
  // directive rule (content routing sent it to reactGate → runtime crash).
  // No JS-framework capability (no manifest, backend, vue) → legacy NEXT_RE
  // content routing, byte-identical (fixtures/sim without manifests rely on it).
  const route = jsGateRoute(filePath);
  if (route === "nextjs") return nextGate(filePath, content, fileLines);
  if (route === "react") return reactGate(filePath, content, fileLines);
  return NEXT_RE.test(content)
    ? nextGate(filePath, content, fileLines)
    : reactGate(filePath, content, fileLines);
}

/**
 * Framework-specific SOLID gate. Dispatches by extension/path to the matching
 * validator (React, Next.js, Laravel, Swift, Go, Rust) and returns a blocking
 * {@link Prompt} when any BLOCKING rule fires, or `null` when clean. Excluded
 * build/dependency paths (node_modules, dist, build, .next, vendor, .build,
 * DerivedData, Pods) early-return `null` to avoid false positives. Go and Rust
 * have no exclusion list yet (no vendor/target FPs reported) — additive only.
 * @param filePath - absolute path of the file being written/edited
 * @param content - the file (or new) content under validation
 * @param fileLines - full on-disk line count (set on Edit so a partial
 *   `new_string` snippet still judges the whole file, mirroring the base
 *   file-size guard / Python `get_full_file_content`). Omit on Write.
 */
export function frameworkSolidGate(filePath: string, content: string, fileLines?: number): Prompt | null {
  if (!filePath || !content) return null;
  // TanStack Router's generated route tree is never edited (Amendment 8 —
  // protected artifact, like the existing protected-path guard).
  if (filePath.endsWith("routeTree.gen.ts")) {
    return {
      kind: "block",
      title: "Generated file",
      reason: `SOLID VIOLATION in ${filePath}: routeTree.gen.ts is generated by TanStack Router — never edit it directly.`,
      actions: ["Edit the source route files instead, then regenerate"],
    };
  }
  let violations: string[] = [];
  if (filePath.endsWith(".php")) {
    if (isExcludedPhpPath(filePath)) return null;
    violations = laravelGate(filePath, content, fileLines);
  } else if (filePath.endsWith(".swift")) {
    if (isExcludedSwiftPath(filePath)) return null;
    violations = swiftGate(filePath, content, fileLines);
  } else if (/\.(tsx|ts|jsx|js)$/.test(filePath)) {
    violations = jsViolations(filePath, content, fileLines);
  } else if (filePath.endsWith(".go")) {
    violations = goGate(filePath, content, fileLines);
  } else if (filePath.endsWith(".rs")) {
    violations = rustGate(filePath, content, fileLines);
  }
  if (violations.length) return block(filePath, violations);
  // Legacy gates clean: the NEW convention rules surface advisory-first —
  // same exclusions as the JS path (build artifacts + self-gate sources).
  if (!/\.(tsx|ts|jsx|js|vue)$/.test(filePath) || isExcludedJsPath(filePath) || isSelfGateSourcePath(filePath)) return null;
  const extended = extendedViolations(filePath, content);
  return extended.length ? rolloutVerdict(block(filePath, extended), true) : null;
}
